name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image jdk:11
        with:
          image: dinospring/jdk
          tags: 11
          directory: ./jdk
          dockerfile: jdk/Dockerfile
          registry: docker.io
          enableBuildKit: true
          buildArgs: |
            JAVA_VERSION=11
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image jdk:17
        with:
          image: dinospring/jdk
          tags: 17
          directory: ./jdk
          dockerfile: jdk/Dockerfile
          registry: docker.io
          enableBuildKit: true
          buildArgs: |
            JAVA_VERSION=17
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image jdk:21
        with:
          image: dinospring/jdk
          tags: 21
          directory: ./jdk
          dockerfile: jdk/Dockerfile
          registry: docker.io
          enableBuildKit: true
          buildArgs: |
            JAVA_VERSION=21
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image jdk:25
        with:
          image: dinospring/jdk
          tags: 25,latest
          directory: ./jdk
          dockerfile: jdk/Dockerfile
          registry: docker.io
          enableBuildKit: true
          buildArgs: |
            JAVA_VERSION=25
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: dinospring/jdk
          provider: dockerhub
          short_description: '🦖dino.dev spring JDK runtime images 😊'
          readme_file: 'README.md'